apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "@helm.chart.name@.fullname" . }}
  labels:
    {{- include "@helm.chart.name@.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "@helm.chart.name@.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "@helm.chart.name@.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "@helm.chart.name@.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "java"
            - "$(JAVA_OPTS)"
            - "-cp"
            - "resources:classes:libs/*"
            - "com.solutechconsulting.k8s.demo.K8sDemoApplication"
          envFrom:
            - configMapRef:
                name: {{ include "@helm.chart.name@.fullname" . }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: management
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: management
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: management
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
